### ISSUE TITLE
修字体

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/oa-web-render#1]
修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体修字体

**Comment by XxLittleCxX** [comment]
怎么复现

**Comment by Dianliang233** [comment]
字型不与语言匹配

例：
https://minecraft.fandom.com/zh/wiki/Minecraft?variant=zh-cn
https://minecraft.fandom.com/zh/wiki/Minecraft?variant=zh-tw
https://minecraft.fandom.com/ja/wiki/Minecraft

**Comment by OasisAkari** [comment]
字体问题似乎和传入的html无关

即使声明一个字体集然后套进去，本地浏览器测试可以看到生效，但传入渲染器依然不生效

**Comment by OasisAkari** [comment]
只要把font family的顺序调一下就好了1111111

**Comment by XxLittleCxX** [comment]
你pr一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Teahouse-Studios/oa-web-render"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月25日(星期五) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Teahouse-Studios/oa-web-render] 修字体 (#1)





 
只要把font family的顺序调一下就好了1111111
