### ISSUE TITLE
?

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/oa-web-render#5]
{"message":"At least `images` must contain more than one image","stack":"Error: At least `images` must contain more than one image\n    at mergeImg (/home/oasisakari/oa-web-render/dist/index.js:235:1755)\n    at /home/oasisakari/oa-web-render/dist/index.js:746:764308\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)"}

**Comment by XxLittleCxX** [comment]
6 给个复现方法

**Comment by OasisAkari** [comment]
[31da6b38-afaf-440c-a2dc-4e4cf427258e.txt](https://github.com/Teahouse-Studios/oa-web-render/files/10250662/31da6b38-afaf-440c-a2dc-4e4cf427258e.txt)

**Comment by XxLittleCxX** [comment]
![image](https://user-images.githubusercontent.com/26459759/208224710-e3bfff4c-d4e3-4b34-916d-e1785f6db08c.png)

6

**Comment by XxLittleCxX** [comment]
这是不是得怪你

**Comment by XxLittleCxX** [comment]
频发吗 不频发的话我改成没高度直接截全 body 算了

**Comment by OasisAkari** [comment]
6

**Comment by OasisAkari** [comment]
只有萌娘百科的infobox会这样
